#!/bin/bash
set -a

DBCONFFILE="/chemotion/app/config/database.yml"

getenv() {
    # $1: env variable name
    # $2: yml key
    # $3: default value

    if [[ -z "$LOGFILE" ]]; then
        LOG2="/dev/null"
    else
        LOG2="${LOGFILE}"
    fi

    # return env variable if its set.
    [[ -n "${!1}" ]] && \
        echo "${!1}" && return 0;

    # check yml file and return if it has a value != ''
    yml=$(yq ".production.$2" "${DBCONFFILE}" 2>>"${LOG2}")
    [[ $? -eq 0 && "$yml" != "null" ]] && \
        echo "${yml}" && return 0;

    # return default value
    echo "$3"
}

PGHOST=$(getenv DB_HOST host db)
PGPORT=$(getenv DB_PORT port 5432)
PGUSER=$(getenv DB_USERNAME username chemotion)
PGPASSWORD=$(getenv DB_PASSWORD password chemotion)
PGDATABASE=$(getenv DB_DATABASE database chemotion)

export PGHOST
export PGPORT
export PGUSER
export PGPASSWORD
export PGDATABASE
