name: Release Chemotion CLI

on:
  push:
    branches:
      - wb_cli3_harivyasi

jobs:
  build-release-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          check-latest: true
      - name: Build Go for linux
        run: |
          cd     chemotion-cli
          go     mod    verify
          go     build  -o chemotion
          mv     chemotion ..
      - name: Release Binary
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            chemotion
