version: '3'
services:
    db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - /home/chemotion/db-data:/var/lib/postgresql/data/
        expose:
            - '5432'
        ports:
            - 5432:5432

    worker:
        image: 'ptrxyz/chemotion:local-dev'
        command: ["start-worker"]
        depends_on:
            - 'db'
        volumes:
            - ./src:/chemotion/app

    eln:
        image: 'ptrxyz/chemotion:local-dev'
        command: ["start-eln"]
        depends_on:
            - 'db'
        expose:
            - '4000'
        ports:
            - 4000:4000
        volumes:
            - ./src:/chemotion/app
