#!/bin/bash
set -a

DBCONFFILE="/chemotion/app/config/database.yml"

getenv() {
    # $1: env variable name
    # $2: yml key
    # $3: default value

    [[ -z "$LOGFILE" ]] && LOGGER="2>/dev/null" || LOGGER="2>>$LOGFILE"

    # return env variable if its set.
    [[ -n "${!1}" ]] && \
        echo ${!1} && return 0;

    # check yml file and return if it has a value != ''
    yml=$(eval yq '.production.'$2 $DBCONFFILE $LOGGER)
    [[ $? -eq 0 && "$yml" != "null" ]] && \
        echo $yml && return 0;
    
    # return default value
    echo "$3"
}

export PGHOST=$(getenv DB_HOST host db)
export PGPORT=$(getenv DB_PORT port 5432)
export PGUSER=$(getenv DB_USERNAME username chemotion)
export PGPASSWORD=$(getenv DB_PASSWORD password chemotion)
export PGDATABASE=$(getenv DB_DATABASE database chemotion)
